"""
End-to-end smoke test for complete user workflow.

Task 23.2: Write end-to-end smoke test
- Start backend via pytest fixture
- Run the full upload → submit → wait for completion → download flow using httpx
- Assert downloaded file is non-empty binary content

This is a higher-level smoke test than 23.1, validating the complete user workflow
from file upload through job execution to output download.

The test uses TestClient with ASGI transport to communicate with the FastAPI app
in-process, simulating the full HTTP request/response cycle that a real frontend
would experience.

Requirements: 1.1-1.6, 6.1-6.7, 7.1-7.6, 8.1-8.3
"""

import asyncio
import io
import json
import os
import struct
import tempfile
from pathlib import Path
from unittest.mock import AsyncMock, MagicMock, Mock, patch

import httpx
import pytest


def create_test_stl_cube() -> bytes:
    """
    Create a minimal valid binary STL file representing a 10mm cube.
    
    Binary STL format:
    - 80 byte header
    - 4 bytes: number of triangles (uint32)
    - For each triangle:
      - 12 bytes: normal vector (3x float32)
      - 36 bytes: 3 vertices, each with x,y,z (9x float32)
      - 2 bytes: attribute byte count (uint16)
    
    A cube has 12 triangles (2 per face, 6 faces).
    """
    header = b"STL 10mm test cube for E2E smoke test" + b"\x00" * (80 - 38)
    
    # Define vertices for a 10mm cube (0 to 10mm in each axis)
    v = [
        (0.0, 0.0, 0.0),  # 0
        (10.0, 0.0, 0.0), # 1
        (10.0, 10.0, 0.0),# 2
        (0.0, 10.0, 0.0), # 3
        (0.0, 0.0, 10.0), # 4
        (10.0, 0.0, 10.0),# 5
        (10.0, 10.0, 10.0),# 6
        (0.0, 10.0, 10.0),# 7
    ]
    
    # Define 12 triangles (2 per face) with outward normals
    triangles = [
        # Bottom face (z=0, normal pointing down)
        ((v[0], v[2], v[1]), (0.0, 0.0, -1.0)),
        ((v[0], v[3], v[2]), (0.0, 0.0, -1.0)),
        # Top face (z=10, normal pointing up)
        ((v[4], v[5], v[6]), (0.0, 0.0, 1.0)),
        ((v[4], v[6], v[7]), (0.0, 0.0, 1.0)),
        # Front face (y=0, normal pointing forward)
        ((v[0], v[1], v[5]), (0.0, -1.0, 0.0)),
        ((v[0], v[5], v[4]), (0.0, -1.0, 0.0)),
        # Back face (y=10, normal pointing backward)
        ((v[3], v[7], v[6]), (0.0, 1.0, 0.0)),
        ((v[3], v[6], v[2]), (0.0, 1.0, 0.0)),
        # Left face (x=0, normal pointing left)
        ((v[0], v[4], v[7]), (-1.0, 0.0, 0.0)),
        ((v[0], v[7], v[3]), (-1.0, 0.0, 0.0)),
        # Right face (x=10, normal pointing right)
        ((v[1], v[2], v[6]), (1.0, 0.0, 0.0)),
        ((v[1], v[6], v[5]), (1.0, 0.0, 0.0)),
    ]
    
    # Pack triangle data
    triangle_data = b""
    for (v1, v2, v3), normal in triangles:
        # Normal vector (3x float32)
        triangle_data += struct.pack("<fff", *normal)
        # Vertex 1
        triangle_data += struct.pack("<fff", *v1)
        # Vertex 2
        triangle_data += struct.pack("<fff", *v2)
        # Vertex 3
        triangle_data += struct.pack("<fff", *v3)
        # Attribute byte count (uint16)
        triangle_data += struct.pack("<H", 0)
    
    # Assemble: header + triangle count + triangle data
    num_triangles = len(triangles)
    return header + struct.pack("<I", num_triangles) + triangle_data


def create_mock_gcode_output() -> bytes:
    """
    Create mock G-code output that simulates what OrcaSlicer would produce.
    
    Returns minimal but valid G-code with basic structure.
    """
    gcode = b"""; Generated by OrcaSlicer (mock)
; Total layers: 50
; Layer height: 0.2mm

; Start G-code
G28 ; Home all axes
G1 Z0.2 F240 ; Move to first layer height

; Layer 1
G1 X50 Y50 E5 F1800 ; Extrude
G1 X100 Y50 E10 F1800
G1 X100 Y100 E15 F1800
G1 X50 Y100 E20 F1800

; Layer 2
G1 Z0.4 F240
G1 X50 Y50 E25 F1800
G1 X100 Y50 E30 F1800
G1 X100 Y100 E35 F1800
G1 X50 Y100 E40 F1800

; End G-code
G28 X0 ; Home X axis
M104 S0 ; Turn off hotend
M140 S0 ; Turn off bed
M84 ; Disable motors
"""
    return gcode


@pytest.fixture
def e2e_workspace(tmp_path):
    """
    Create a complete test environment for E2E testing.
    
    Sets up:
    - Workspace directories
    - Mock CLI binary
    - Mock profile files
    - Environment variables
    """
    workspace = tmp_path / "workspace"
    workspace.mkdir()
    
    # Create required subdirectories
    (workspace / "sessions").mkdir()
    (workspace / "jobs").mkdir()
    (workspace / "custom_profiles").mkdir()
    
    # Create mock CLI binary
    cli_dir = tmp_path / "orca_cli"
    cli_dir.mkdir()
    fake_cli = cli_dir / "orca-slicer"
    fake_cli.write_text("#!/bin/bash\necho 'Mock CLI'\n")
    fake_cli.chmod(0o755)
    
    # Create mock profiles directory structure
    profiles_root = tmp_path / "orca_cli" / "resources" / "profiles"
    profiles_root.mkdir(parents=True)
    
    manufacturer_dir = profiles_root / "Generic"
    manufacturer_dir.mkdir()
    
    # Machine profile
    machine_dir = manufacturer_dir / "machine"
    machine_dir.mkdir()
    printer_profile = {
        "name": "Generic Printer",
        "printable_area": [[0, 0], [220, 0], [220, 220], [0, 220]],
        "bed_shape": [[0, 0], [220, 0], [220, 220], [0, 220]],
        "nozzle_diameter": ["0.4"],
    }
    (machine_dir / "generic.json").write_text(json.dumps(printer_profile))
    
    # Process profile
    process_dir = manufacturer_dir / "process"
    process_dir.mkdir()
    process_profile = {
        "name": "Generic 0.20mm",
        "layer_height": "0.2",
        "wall_loops": "3",
        "sparse_infill_density": "15%",
    }
    (process_dir / "generic_0.2mm.json").write_text(json.dumps(process_profile))
    
    # Filament profile
    filament_dir = manufacturer_dir / "filament"
    filament_dir.mkdir()
    filament_profile = {
        "name": "Generic PLA",
        "filament_type": "PLA",
        "temperature": ["210"],
        "bed_temperature": ["60"],
    }
    (filament_dir / "generic_pla.json").write_text(json.dumps(filament_profile))
    
    # Set environment variables. TMP_ROOT points at the same directory as
    # WORKSPACE_ROOT here (the sessions/jobs subdirs created above are
    # shared) since this smoke test only cares about end-to-end wiring,
    # not the persistent/ephemeral split itself — see config.py's
    # tmp_root docstring.
    os.environ["WORKSPACE_ROOT"] = str(workspace)
    os.environ["TMP_ROOT"] = str(workspace)
    os.environ["ORCA_CLI_PATH"] = str(fake_cli)
    os.environ["API_SECRET"] = "e2e_test_secret_key_12345"
    os.environ["MAX_CONCURRENT_JOBS"] = "2"
    os.environ["JOB_TIMEOUT_SECONDS"] = "300"
    
    yield {
        "workspace": workspace,
        "cli_path": fake_cli,
        "profiles_root": profiles_root,
        "printer_profile": "Generic/machine/generic.json",
        "process_profile": "Generic/process/generic_0.2mm.json",
        "filament_profile": "Generic/filament/generic_pla.json",
    }
    
    # Cleanup environment
    for key in ["WORKSPACE_ROOT", "TMP_ROOT", "ORCA_CLI_PATH", "API_SECRET", "MAX_CONCURRENT_JOBS", "JOB_TIMEOUT_SECONDS"]:
        if key in os.environ:
            del os.environ[key]


class MockCLIProcess:
    """
    Mock CLI process that simulates OrcaSlicer execution.
    
    Simulates:
    - Async process execution
    - Progress output on stdout
    - Exit with status code 0
    - Creation of output G-code file
    """
    
    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.returncode = 0
        self._stdout_data = [
            b'{"plate_index": 0, "plate_count": 1, "plate_percent": 0, "total_percent": 0, "message": "Initializing"}\n',
            b'{"plate_index": 0, "plate_count": 1, "plate_percent": 25, "total_percent": 25, "message": "Slicing layer 10/40"}\n',
            b'{"plate_index": 0, "plate_count": 1, "plate_percent": 50, "total_percent": 50, "message": "Slicing layer 20/40"}\n',
            b'{"plate_index": 0, "plate_count": 1, "plate_percent": 75, "total_percent": 75, "message": "Slicing layer 30/40"}\n',
            b'{"plate_index": 0, "plate_count": 1, "plate_percent": 100, "total_percent": 100, "message": "Slicing complete"}\n',
        ]
        self._read_index = 0
        self._file_created = False
    
    async def communicate(self):
        """Simulate communicate() that returns stdout/stderr."""
        await asyncio.sleep(0.1)  # Simulate some processing time
        
        # Create output file before returning
        if not self._file_created:
            self.output_dir.mkdir(parents=True, exist_ok=True)
            gcode_output = self.output_dir / "plate_1.gcode"
            gcode_output.write_bytes(create_mock_gcode_output())
            self._file_created = True
        
        return (b"".join(self._stdout_data), b"")
    
    async def wait(self):
        """Simulate wait() that waits for process to finish."""
        # Create output file before finishing
        if not self._file_created:
            self.output_dir.mkdir(parents=True, exist_ok=True)
            gcode_output = self.output_dir / "plate_1.gcode"
            gcode_output.write_bytes(create_mock_gcode_output())
            self._file_created = True
        
        await asyncio.sleep(0.1)
        return self.returncode
    
    @property
    def stdout(self):
        """Mock stdout as an async reader."""
        class MockReader:
            def __init__(self, data, parent):
                self.data = data
                self.parent = parent
            
            async def readline(self):
                # Create output file on first readline
                if self.parent._read_index == 0 and not self.parent._file_created:
                    self.parent.output_dir.mkdir(parents=True, exist_ok=True)
                    gcode_output = self.parent.output_dir / "plate_1.gcode"
                    gcode_output.write_bytes(create_mock_gcode_output())
                    self.parent._file_created = True
                
                if self.parent._read_index < len(self.parent._stdout_data):
                    line = self.parent._stdout_data[self.parent._read_index]
                    self.parent._read_index += 1
                    await asyncio.sleep(0.02)  # Simulate gradual output
                    return line
                return b""
        
        return MockReader(self._stdout_data, self)


@pytest.mark.asyncio
async def test_e2e_full_workflow_smoke(e2e_workspace):
    """
    End-to-end smoke test for the complete user workflow.
    
    Tests the full flow:
    1. Upload STL file
    2. Submit slicing job
    3. Wait for job to complete
    4. Download output G-code
    5. Verify output is non-empty binary
    
    This test simulates the complete user experience from uploading a model
    to downloading the sliced G-code.
    
    Task 23.2: E2E smoke test
    Requirements: 1.1-1.6, 6.1-6.7, 7.1-7.6, 8.1-8.3
    """
    # Clear any cached modules
    import sys
    for module in list(sys.modules.keys()):
        if module.startswith('app.'):
            del sys.modules[module]
    
    # Mock the CLI process execution
    async def mock_create_subprocess_exec(*args, **kwargs):
        # Extract output directory from args
        output_dir = None
        for i, arg in enumerate(args):
            if arg == "--outputdir" and i + 1 < len(args):
                output_dir = Path(args[i + 1])
                break
        
        if output_dir is None:
            output_dir = e2e_workspace["workspace"] / "jobs" / "default" / "output"
        
        return MockCLIProcess(output_dir)
    
    # Patch subprocess creation and database initialization
    with patch("app.database.init_db", new_callable=AsyncMock), \
         patch("app.cleanup.run_cleanup_loop", return_value=AsyncMock()), \
         patch("asyncio.create_subprocess_exec", side_effect=mock_create_subprocess_exec):
        
        # Initialize auth
        from app.auth import init_auth
        init_auth("e2e_test_secret_key_12345")
        
        # Import app
        from app.main import app
        from app.database import get_db
        from app.config import settings
        
        # Override profiles_root to use our mock
        type(settings).profiles_root = property(lambda self: e2e_workspace["profiles_root"])
        
        # Create shared database file for testing (not :memory: so it's shared across connections)
        import aiosqlite
        
        db_path = e2e_workspace["workspace"] / "test.db"
        
        # Initialize database with schema
        async with aiosqlite.connect(db_path) as init_db:
            await init_db.execute("PRAGMA foreign_keys = ON")
            
            # Create schema
            await init_db.execute("""
                CREATE TABLE files (
                    file_id TEXT PRIMARY KEY,
                    session_id TEXT NOT NULL,
                    original_name TEXT NOT NULL,
                    extension TEXT NOT NULL CHECK (extension IN ('stl','3mf','obj','amf','json')),
                    size_bytes INTEGER NOT NULL,
                    storage_path TEXT NOT NULL,
                    uploaded_at TEXT NOT NULL
                )
            """)
            
            await init_db.execute("""
                CREATE TABLE jobs (
                    job_id TEXT PRIMARY KEY,
                    session_id TEXT NOT NULL,
                    submitted_at TEXT NOT NULL,
                    started_at TEXT,
                    completed_at TEXT,
                    status TEXT NOT NULL DEFAULT 'queued'
                        CHECK (status IN ('queued','running','completed','failed','timed_out')),
                    action_type TEXT NOT NULL,
                    cli_args TEXT NOT NULL,
                    exit_code INTEGER,
                    error_message TEXT,
                    output_dir TEXT NOT NULL
                )
            """)
            
            await init_db.execute("""
                CREATE TABLE output_files (
                    output_file_id TEXT PRIMARY KEY,
                    job_id TEXT NOT NULL REFERENCES jobs(job_id) ON DELETE CASCADE,
                    filename TEXT NOT NULL,
                    size_bytes INTEGER NOT NULL,
                    storage_path TEXT NOT NULL,
                    created_at TEXT NOT NULL
                )
            """)
            
            await init_db.commit()
        
        async def get_test_db():
            """Test database connection factory."""
            db = await aiosqlite.connect(db_path)
            await db.execute("PRAGMA foreign_keys = ON")
            db.row_factory = aiosqlite.Row
            
            try:
                yield db
            finally:
                await db.close()
        
        app.dependency_overrides[get_db] = get_test_db
        
        # Mock job manager with the shared database
        from app.job_manager import JobManager
        real_job_manager = JobManager(settings, str(db_path))
        await real_job_manager.start()  # Start the job manager to process jobs
        app.state.job_manager = real_job_manager
        
        # Mock WebSocket manager
        from app.ws_manager import WebSocketManager
        app.state.ws_manager = WebSocketManager()
        
        try:
            # Create HTTP client with ASGI transport
            from httpx import ASGITransport
            transport = ASGITransport(app=app)
            
            async with httpx.AsyncClient(transport=transport, base_url="http://test", timeout=30.0) as client:
                
                # Step 1: Upload STL file
                print("\n=== Step 1: Upload STL file ===")
                stl_content = create_test_stl_cube()
                print(f"Created test STL: {len(stl_content)} bytes")
                
                upload_response = await client.post(
                    "/api/files/upload",
                    files={"file": ("test_cube.stl", io.BytesIO(stl_content), "application/octet-stream")},
                    headers={"Authorization": "Bearer e2e_test_secret_key_12345"},
                )
                
                assert upload_response.status_code == 200, f"Upload failed: {upload_response.text}"
                upload_data = upload_response.json()
                file_id = upload_data["file_id"]
                print(f"✓ File uploaded successfully: {file_id}")
                assert upload_data["filename"] == "test_cube.stl"
                assert upload_data["extension"] == "stl"
                assert upload_data["size_bytes"] == len(stl_content)
                
                # Step 2: Submit slicing job
                print("\n=== Step 2: Submit slicing job ===")
                job_request = {
                    "file_ids": [file_id],
                    "printer_profile_path": e2e_workspace["printer_profile"],
                    "process_profile_path": e2e_workspace["process_profile"],
                    "filament_profile_paths": [e2e_workspace["filament_profile"]],
                    "action": "slice",
                    "plate_number": 0,
                }
                
                job_response = await client.post(
                    "/api/jobs",
                    json=job_request,
                    headers={"Authorization": "Bearer e2e_test_secret_key_12345"},
                )
                
                assert job_response.status_code == 200, f"Job submission failed: {job_response.text}"
                job_data = job_response.json()
                job_id = job_data["job_id"]
                print(f"✓ Job submitted successfully: {job_id}")
                assert job_data["status"] == "queued"
                
                # Step 3: Wait for job completion (poll status)
                print("\n=== Step 3: Wait for job completion ===")
                max_attempts = 30  # 30 seconds max
                poll_interval = 1.0  # 1 second
                
                for attempt in range(max_attempts):
                    await asyncio.sleep(poll_interval)
                    
                    status_response = await client.get(
                        f"/api/jobs/{job_id}",
                        headers={"Authorization": "Bearer e2e_test_secret_key_12345"},
                    )
                    
                    assert status_response.status_code == 200, f"Status check failed: {status_response.text}"
                    job_status = status_response.json()
                    
                    current_status = job_status["status"]
                    print(f"  Attempt {attempt + 1}/{max_attempts}: status = {current_status}")
                    
                    if current_status == "completed":
                        print(f"✓ Job completed successfully after {attempt + 1} attempts")
                        break
                    elif current_status == "failed":
                        pytest.fail(f"Job failed: {job_status.get('error_message', 'Unknown error')}")
                    elif current_status == "timed_out":
                        pytest.fail("Job timed out")
                else:
                    pytest.fail(f"Job did not complete within {max_attempts} seconds")
                
                # Verify job completion details
                assert job_status["exit_code"] == 0, "Expected exit code 0 for successful job"
                assert job_status["action_type"] == "slice"
                
                # Step 4: Get output files
                print("\n=== Step 4: Get output files ===")
                outputs_response = await client.get(
                    f"/api/jobs/{job_id}/outputs",
                    headers={"Authorization": "Bearer e2e_test_secret_key_12345"},
                )
                
                assert outputs_response.status_code == 200, f"Outputs fetch failed: {outputs_response.text}"
                outputs_data = outputs_response.json()
                
                print(f"Job status: {outputs_data['status']}")
                print(f"Output files: {len(outputs_data['output_files'])}")
                
                assert outputs_data["status"] == "completed"
                assert len(outputs_data["output_files"]) >= 1, "Expected at least one output file"
                
                output_file = outputs_data["output_files"][0]
                print(f"✓ Found output file: {output_file['filename']} ({output_file['size_bytes']} bytes)")
                assert output_file["filename"].endswith(".gcode"), "Expected .gcode output"
                assert output_file["size_bytes"] > 0, "Expected non-empty output file"
                
                # Step 5: Download output file
                print("\n=== Step 5: Download output file ===")
                download_url = output_file["download_url"]
                
                download_response = await client.get(
                    download_url,
                    headers={"Authorization": "Bearer e2e_test_secret_key_12345"},
                )
                
                assert download_response.status_code == 200, f"Download failed: {download_response.status_code}"
                downloaded_content = download_response.content
                
                print(f"✓ Downloaded {len(downloaded_content)} bytes")
                
                # Verify downloaded content is non-empty binary
                assert len(downloaded_content) > 0, "Downloaded file is empty"
                assert isinstance(downloaded_content, bytes), "Downloaded content should be bytes"
                
                # Verify it looks like G-code (should contain G-code commands)
                content_str = downloaded_content.decode("utf-8", errors="ignore")
                assert "G1" in content_str or "G28" in content_str, "Downloaded content doesn't look like G-code"
                
                print(f"✓ Downloaded content verified (contains G-code commands)")
                
                # Final success
                print("\n=== E2E Smoke Test PASSED ===")
                print(f"Successfully completed full workflow:")
                print(f"  - Uploaded: {file_id}")
                print(f"  - Executed job: {job_id}")
                print(f"  - Downloaded: {output_file['filename']} ({len(downloaded_content)} bytes)")
                
        finally:
            app.dependency_overrides.clear()
            if hasattr(app.state, "job_manager"):
                await app.state.job_manager.stop()
