"""
Tests for POST /api/jobs/{job_id}/thumbnail.

Native OrcaSlicer's CLI has no way to generate a gcode thumbnail itself —
its `export_thumbnails_to_file` (libslic3r/GCode/Thumbnails.hpp) early-
returns whenever no thumbnail generator callback is registered, and the
CLI entry point (OrcaSlicer.cpp) never registers one (that only happens
in the desktop GUI's OpenGL-backed BackgroundSlicingProcess). This
endpoint lets the frontend upload a PNG it rendered itself (a snapshot of
the Prepare-tab's live Three.js viewport), registers it as a normal job
output file, AND splices it directly into the plate's .gcode as a
byte-for-byte equivalent of the `; THUMBNAIL_BLOCK_START ... ; thumbnail
begin WxH size ... ; thumbnail end ... ; THUMBNAIL_BLOCK_END` comment
block native's own GCode.cpp would have written — since that block is
pure ASCII comments, it can be spliced in after the fact without needing
the CLI to cooperate at all.

Requirements: (feature request) "Add png thumbnail when you slice the
stl to create gcode." / "since the thumbnail block is just a comment
block, can we insert a block of comment to the gcode with orca slicer
cli?"
"""

import json
from unittest.mock import AsyncMock, patch

import pytest
from fastapi.testclient import TestClient

from app.routers.jobs import _splice_thumbnail_into_gcode

# Minimal valid 1x1 PNG (smallest possible PNG file, magic bytes + IHDR/
# IDAT/IEND chunks for a 1x1 transparent pixel).
_TINY_PNG = bytes.fromhex(
    "89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c489"
    "0000000a49444154789c6360000002000100ffff03000006000557bfabd4000000"
    "0049454e44ae426082"
)


def _init_app(job_row, tmp_output_dir=None):
    """Set up auth + a mocked DB whose `jobs` row is `job_row`, patching
    out the real database/cleanup-loop startup hooks so the app can be
    imported and driven via TestClient without a real SQLite file."""
    from app.auth import init_auth
    init_auth("test-secret-12345")

    from app.main import app
    from app.database import get_db

    async def mock_get_db():
        mock_db = AsyncMock()

        async def mock_execute(query, params=None, *args, **kwargs):
            cursor = AsyncMock()
            if query.strip().upper().startswith("SELECT"):
                cursor.fetchone = AsyncMock(return_value=job_row)
            return cursor

        mock_db.execute = mock_execute
        mock_db.commit = AsyncMock()
        yield mock_db

    app.dependency_overrides[get_db] = mock_get_db
    return app


def test_upload_thumbnail_success(tmp_path):
    """A valid PNG uploaded for a completed job is written to the job's
    output directory and registered as an output file, returning its
    summary (filename, size_bytes, download_url)."""
    output_dir = tmp_path / "output"
    output_dir.mkdir()

    job_row = {"status": "completed", "output_dir": str(output_dir)}

    with patch("app.database.init_db", new_callable=AsyncMock), \
         patch("app.cleanup.run_cleanup_loop", return_value=AsyncMock()):
        app = _init_app(job_row)
        try:
            client = TestClient(app)
            response = client.post(
                "/api/jobs/test-job-id/thumbnail",
                headers={
                    "Authorization": "Bearer test-secret-12345",
                    "Content-Type": "image/png",
                },
                content=_TINY_PNG,
            )

            assert response.status_code == 200
            data = response.json()
            assert data["filename"] == "thumbnail.png"
            assert data["size_bytes"] == len(_TINY_PNG)
            assert data["download_url"] == "/api/jobs/test-job-id/outputs/thumbnail.png"

            # File actually written to disk in the job's output directory.
            written = output_dir / "thumbnail.png"
            assert written.exists()
            assert written.read_bytes() == _TINY_PNG
        finally:
            app.dependency_overrides.clear()


def test_upload_thumbnail_splices_block_into_existing_gcode(tmp_path):
    """Uploading a thumbnail for a job that already produced a
    plate_N.gcode file splices the native-format comment block directly
    into that file, immediately after HEADER_BLOCK_END — matching where
    GCode.cpp's `_do_export` writes it for a real desktop-GUI slice."""
    output_dir = tmp_path / "output"
    output_dir.mkdir()
    gcode_path = output_dir / "plate_1.gcode"
    gcode_path.write_text(
        "; HEADER_BLOCK_START\n"
        "; generated by OrcaSlicer 2.4.2\n"
        "; HEADER_BLOCK_END\n\n"
        "; CONFIG_BLOCK_START\n"
        "; CONFIG_BLOCK_END\n\n"
        "G28\n"
    )
    job_row = {"status": "completed", "output_dir": str(output_dir)}

    with patch("app.database.init_db", new_callable=AsyncMock), \
         patch("app.cleanup.run_cleanup_loop", return_value=AsyncMock()):
        app = _init_app(job_row)
        try:
            client = TestClient(app)
            response = client.post(
                "/api/jobs/test-job-id/thumbnail",
                headers={"Authorization": "Bearer test-secret-12345"},
                content=_TINY_PNG,
            )
            assert response.status_code == 200

            text = gcode_path.read_text()
            assert "; THUMBNAIL_BLOCK_START" in text
            assert "; thumbnail begin 1x1" in text
            assert "; thumbnail end" in text
            assert "; THUMBNAIL_BLOCK_END" in text
            # Placed after the header block, before the rest of the file.
            header_idx = text.index("; HEADER_BLOCK_END")
            thumb_idx = text.index("; THUMBNAIL_BLOCK_START")
            gcode_idx = text.index("G28")
            assert header_idx < thumb_idx < gcode_idx
            # Original gcode content is preserved, not clobbered.
            assert "G28" in text
        finally:
            app.dependency_overrides.clear()


def test_upload_thumbnail_re_upload_replaces_spliced_block(tmp_path):
    """Uploading a second thumbnail for the same job replaces the
    previously-spliced block rather than duplicating it."""
    output_dir = tmp_path / "output"
    output_dir.mkdir()
    gcode_path = output_dir / "plate_1.gcode"
    gcode_path.write_text(
        "; HEADER_BLOCK_START\n; HEADER_BLOCK_END\n\nG28\n"
    )
    job_row = {"status": "completed", "output_dir": str(output_dir)}

    with patch("app.database.init_db", new_callable=AsyncMock), \
         patch("app.cleanup.run_cleanup_loop", return_value=AsyncMock()):
        app = _init_app(job_row)
        try:
            client = TestClient(app)
            client.post(
                "/api/jobs/test-job-id/thumbnail",
                headers={"Authorization": "Bearer test-secret-12345"},
                content=_TINY_PNG,
            )
            client.post(
                "/api/jobs/test-job-id/thumbnail",
                headers={"Authorization": "Bearer test-secret-12345"},
                content=_TINY_PNG,
            )

            text = gcode_path.read_text()
            assert text.count("; THUMBNAIL_BLOCK_START") == 1
            assert text.count("; thumbnail begin") == 1
        finally:
            app.dependency_overrides.clear()


class TestSpliceThumbnailIntoGcode:
    """Direct unit tests for the splicing helper itself."""

    def test_splices_after_header_block_end(self, tmp_path):
        gcode_path = tmp_path / "plate_1.gcode"
        gcode_path.write_text(
            "; HEADER_BLOCK_START\n; foo\n; HEADER_BLOCK_END\n\nG1 X0\n"
        )
        _splice_thumbnail_into_gcode(gcode_path, _TINY_PNG)

        text = gcode_path.read_text()
        assert text.index("; HEADER_BLOCK_END") < text.index("; THUMBNAIL_BLOCK_START")
        assert text.index("; THUMBNAIL_BLOCK_START") < text.index("G1 X0")

    def test_falls_back_to_prepend_when_no_header_block(self, tmp_path):
        """If a gcode file doesn't have a recognizable HEADER_BLOCK_END
        (unexpected shape), the thumbnail is still added rather than
        silently dropped — prepended to the top of the file."""
        gcode_path = tmp_path / "plate_1.gcode"
        gcode_path.write_text("G1 X0\n")
        _splice_thumbnail_into_gcode(gcode_path, _TINY_PNG)

        text = gcode_path.read_text()
        assert text.index("; THUMBNAIL_BLOCK_START") < text.index("G1 X0")

    def test_base64_payload_round_trips_to_original_png_bytes(self, tmp_path):
        """The base64 data embedded in the block, once line-unwrapped and
        decoded, reproduces the exact original PNG bytes — this is the
        actual native gcode-thumbnail-viewer contract."""
        import base64
        import re as re_module

        gcode_path = tmp_path / "plate_1.gcode"
        gcode_path.write_text("; HEADER_BLOCK_START\n; HEADER_BLOCK_END\n\nG1\n")
        _splice_thumbnail_into_gcode(gcode_path, _TINY_PNG)

        text = gcode_path.read_text()
        match = re_module.search(
            r"; thumbnail begin \d+x\d+ \d+\n(.*?)\n; thumbnail end",
            text,
            re_module.DOTALL,
        )
        assert match is not None
        b64_lines = [line[2:] for line in match.group(1).split("\n")]
        decoded = base64.b64decode("".join(b64_lines))
        assert decoded == _TINY_PNG

    def test_re_splicing_replaces_rather_than_duplicates(self, tmp_path):
        gcode_path = tmp_path / "plate_1.gcode"
        gcode_path.write_text("; HEADER_BLOCK_START\n; HEADER_BLOCK_END\n\nG1\n")
        _splice_thumbnail_into_gcode(gcode_path, _TINY_PNG)
        _splice_thumbnail_into_gcode(gcode_path, _TINY_PNG)

        text = gcode_path.read_text()
        assert text.count("; THUMBNAIL_BLOCK_START") == 1
        assert "G1" in text


def test_upload_thumbnail_rejects_job_not_found():
    """404 when the job_id doesn't exist."""
    with patch("app.database.init_db", new_callable=AsyncMock), \
         patch("app.cleanup.run_cleanup_loop", return_value=AsyncMock()):
        app = _init_app(job_row=None)
        try:
            client = TestClient(app)
            response = client.post(
                "/api/jobs/nonexistent/thumbnail",
                headers={"Authorization": "Bearer test-secret-12345"},
                content=_TINY_PNG,
            )
            assert response.status_code == 404
        finally:
            app.dependency_overrides.clear()


def test_upload_thumbnail_rejects_job_not_completed(tmp_path):
    """409 when the job hasn't finished yet — a thumbnail is meaningless
    for a job that hasn't produced any output files."""
    output_dir = tmp_path / "output"
    output_dir.mkdir()
    job_row = {"status": "running", "output_dir": str(output_dir)}

    with patch("app.database.init_db", new_callable=AsyncMock), \
         patch("app.cleanup.run_cleanup_loop", return_value=AsyncMock()):
        app = _init_app(job_row)
        try:
            client = TestClient(app)
            response = client.post(
                "/api/jobs/test-job-id/thumbnail",
                headers={"Authorization": "Bearer test-secret-12345"},
                content=_TINY_PNG,
            )
            assert response.status_code == 409
        finally:
            app.dependency_overrides.clear()


def test_upload_thumbnail_rejects_empty_body(tmp_path):
    """422 when the request body is empty."""
    output_dir = tmp_path / "output"
    output_dir.mkdir()
    job_row = {"status": "completed", "output_dir": str(output_dir)}

    with patch("app.database.init_db", new_callable=AsyncMock), \
         patch("app.cleanup.run_cleanup_loop", return_value=AsyncMock()):
        app = _init_app(job_row)
        try:
            client = TestClient(app)
            response = client.post(
                "/api/jobs/test-job-id/thumbnail",
                headers={"Authorization": "Bearer test-secret-12345"},
                content=b"",
            )
            assert response.status_code == 422
        finally:
            app.dependency_overrides.clear()


def test_upload_thumbnail_rejects_non_png_body(tmp_path):
    """422 when the body doesn't start with the PNG magic bytes, even if
    the client claims Content-Type: image/png — the Content-Type header
    alone must not be trusted."""
    output_dir = tmp_path / "output"
    output_dir.mkdir()
    job_row = {"status": "completed", "output_dir": str(output_dir)}

    with patch("app.database.init_db", new_callable=AsyncMock), \
         patch("app.cleanup.run_cleanup_loop", return_value=AsyncMock()):
        app = _init_app(job_row)
        try:
            client = TestClient(app)
            response = client.post(
                "/api/jobs/test-job-id/thumbnail",
                headers={
                    "Authorization": "Bearer test-secret-12345",
                    "Content-Type": "image/png",
                },
                content=b"not a real png file at all",
            )
            assert response.status_code == 422
        finally:
            app.dependency_overrides.clear()


def test_upload_thumbnail_requires_authentication(tmp_path):
    """401 (or equivalent) when no Authorization header is provided."""
    output_dir = tmp_path / "output"
    output_dir.mkdir()
    job_row = {"status": "completed", "output_dir": str(output_dir)}

    with patch("app.database.init_db", new_callable=AsyncMock), \
         patch("app.cleanup.run_cleanup_loop", return_value=AsyncMock()):
        app = _init_app(job_row)
        try:
            client = TestClient(app)
            response = client.post(
                "/api/jobs/test-job-id/thumbnail",
                content=_TINY_PNG,
            )
            assert response.status_code in (401, 403)
        finally:
            app.dependency_overrides.clear()
