/**
 * FilamentConfigDialog
 *
 * Data-driven filament settings editor.  The tab/section/field structure is
 * loaded from /data/filament_config_dialog_options.json, generated by
 * scripts/extract_filament_config_options.py.
 *
 * Change tracking, autosave and Save As behaviour mirror PrinterConfigDialog.
 *
 * To update field definitions after an OrcaSlicer upgrade:
 *   python3 scripts/extract_filament_config_options.py
 */

import React, { useEffect, useRef, useState, useCallback } from 'react';
import { X, Save, ChevronDown, RotateCcw } from 'lucide-react';
import { apiClient } from '../../api/client';

// ---------------------------------------------------------------------------
// Schema types (shared with printer dialog)
// ---------------------------------------------------------------------------

interface FieldOption { value: string; label: string }
interface FieldDef {
  key: string; label: string;
  type: string;
  unit?: string;
  options?: FieldOption[];
  default?: string;
}
interface SectionDef { label: string; fields: FieldDef[] }
interface TabDef     { id: string; label: string; sections: SectionDef[] }
interface OptionsDef { tabs: TabDef[] }

// ---------------------------------------------------------------------------
// Filament-specific paired rows (primary → secondary, shown on one row)
// ---------------------------------------------------------------------------

const PAIRED_ROWS: Record<string, string> = {
  nozzle_temperature_initial_layer:       'nozzle_temperature',
  nozzle_temperature_range_low:           'nozzle_temperature_range_high',
  supertack_plate_temp_initial_layer:     'supertack_plate_temp',
  cool_plate_temp_initial_layer:          'cool_plate_temp',
  textured_cool_plate_temp_initial_layer: 'textured_cool_plate_temp',
  eng_plate_temp_initial_layer:           'eng_plate_temp',
  hot_plate_temp_initial_layer:           'hot_plate_temp',
  textured_plate_temp_initial_layer:      'textured_plate_temp',
  fan_min_speed:                          'fan_cooling_layer_time',
  fan_max_speed:                          'slow_down_layer_time',
  chamber_temperature:                    'chamber_minimal_temperature',
  activate_air_filtration_during_print:   'during_print_exhaust_fan_speed',
  activate_air_filtration_on_completion:  'complete_print_exhaust_fan_speed',
};
const PAIRED_SECONDARY = new Set(Object.values(PAIRED_ROWS));

// Labels for paired rows (shown in the row header instead of the primary key label)
const PAIRED_ROW_LABELS: Record<string, string> = {
  nozzle_temperature_initial_layer:       'Nozzle temperature',
  nozzle_temperature_range_low:           'Recommended nozzle temperature',
  supertack_plate_temp_initial_layer:     'Cool Plate (SuperTack)',
  cool_plate_temp_initial_layer:          'Cool Plate',
  textured_cool_plate_temp_initial_layer: 'Textured Cool Plate',
  eng_plate_temp_initial_layer:           'Engineering Plate',
  hot_plate_temp_initial_layer:           'Smooth PEI Plate / High Temp Plate',
  textured_plate_temp_initial_layer:      'Textured PEI Plate',
  fan_min_speed:                          'Min fan speed threshold',
  fan_max_speed:                          'Max fan speed threshold',
  chamber_temperature:                    'Chamber temperature',
  activate_air_filtration_during_print:   'During print',
  activate_air_filtration_on_completion:  'Complete print',
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function firstVal(v: unknown): string {
  if (v === undefined || v === null) return '';
  if (Array.isArray(v)) { const f = v[0]; return (f === undefined || f === null) ? '' : String(f); }
  return String(v);
}
function boolVal(v: unknown): boolean {
  return ['1','true'].includes(firstVal(v).toLowerCase());
}
function valuesEqual(a: unknown, b: unknown): boolean {
  return firstVal(a) === firstVal(b);
}

// ---------------------------------------------------------------------------
// Primitives
// ---------------------------------------------------------------------------

const TextInput: React.FC<{
  value: string; onChange: (v: string) => void;
  placeholder?: string; className?: string; changed?: boolean;
}> = ({ value, onChange, placeholder, className, changed }) => (
  <input type="text" value={value} onChange={e => onChange(e.target.value)} placeholder={placeholder}
    className={`px-2 py-1 border rounded text-sm text-white focus:outline-none focus:ring-1
      focus:ring-teal-500 w-full transition-colors
      ${changed ? 'bg-teal-900/40 border-teal-500' : 'bg-gray-700 border-gray-600'}
      ${className ?? ''}`} />
);

const SelectInput: React.FC<{
  value: string; options: FieldOption[]; onChange: (v: string) => void; changed?: boolean;
}> = ({ value, options, onChange, changed }) => {
  const clean = (s: string) => s.replace(/^L\(u?8?"(.+)"\)$/, '$1').replace(/^L\("(.+)"$/, '$1');
  return (
    <div className="relative flex-1">
      <select value={value} onChange={e => onChange(e.target.value)}
        className={`w-full px-2 py-1 border rounded text-sm text-white focus:outline-none
          focus:ring-1 focus:ring-teal-500 appearance-none pr-7 transition-colors
          ${changed ? 'bg-teal-900/40 border-teal-500' : 'bg-gray-700 border-gray-600'}`}>
        {options.map(o => <option key={o.value} value={o.value}>{clean(o.label)}</option>)}
      </select>
      <ChevronDown className="absolute right-2 top-1/2 -translate-y-1/2 w-3 h-3 text-gray-400 pointer-events-none" />
    </div>
  );
};

const ResetBtn: React.FC<{ onClick: () => void }> = ({ onClick }) => (
  <button onClick={onClick} title="Reset to original value"
    className="flex-shrink-0 p-1 rounded text-teal-400 hover:text-white hover:bg-gray-700 transition-colors">
    <RotateCcw className="w-3.5 h-3.5" />
  </button>
);

// ---------------------------------------------------------------------------
// Save As dialog
// ---------------------------------------------------------------------------

const SaveAsDialog: React.FC<{
  isOpen: boolean; defaultName: string;
  onConfirm: (n: string) => void; onCancel: () => void;
}> = ({ isOpen, defaultName, onConfirm, onCancel }) => {
  const [name, setName] = useState(defaultName);
  useEffect(() => { if (isOpen) setName(defaultName); }, [isOpen, defaultName]);
  if (!isOpen) return null;
  return (
    <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-[10000]"
      onClick={e => { if (e.target === e.currentTarget) onCancel(); }}>
      <div className="bg-gray-800 rounded-lg shadow-2xl p-6 w-[440px] max-w-[95vw]">
        <h2 className="text-white font-semibold text-base mb-4">Save filament config</h2>
        <label className="block text-sm text-gray-300 mb-1">Config name</label>
        <input type="text" value={name} onChange={e => setName(e.target.value)}
          onKeyDown={e => { if (e.key === 'Enter' && name.trim()) onConfirm(name.trim()); }}
          autoFocus
          className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded text-sm text-white
            focus:outline-none focus:ring-1 focus:ring-teal-500 mb-5" />
        <div className="flex justify-end gap-3">
          <button onClick={onCancel}
            className="px-4 py-2 text-sm text-gray-300 bg-gray-700 hover:bg-gray-600 rounded transition-colors">
            Cancel
          </button>
          <button onClick={() => name.trim() && onConfirm(name.trim())} disabled={!name.trim()}
            className="px-4 py-2 text-sm text-white bg-teal-600 hover:bg-teal-500 disabled:opacity-50
              rounded transition-colors flex items-center gap-1.5">
            <Save className="w-4 h-4" /> Save
          </button>
        </div>
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Field row — change-aware
// ---------------------------------------------------------------------------

interface FieldRowProps {
  def: FieldDef; value: unknown; baseValue: unknown;
  pairedDef?: FieldDef; pairedValue?: unknown; pairedBaseValue?: unknown;
  rowLabel?: string;
  onChange: (key: string, v: unknown) => void;
  onReset: (key: string) => void;
}

const FieldRow: React.FC<FieldRowProps> = ({
  def, value, baseValue, pairedDef, pairedValue, pairedBaseValue, rowLabel, onChange, onReset,
}) => {
  const type         = def.type;
  const changed      = !valuesEqual(value, baseValue);
  const pairedChg    = pairedDef ? !valuesEqual(pairedValue, pairedBaseValue) : false;
  const displayLabel = rowLabel ?? def.label;

  // G-code textarea
  if (type === 'gcode') {
    return (
      <div className={`flex flex-col gap-1 py-2 border-b border-gray-700/50 ${changed ? 'bg-teal-900/10' : ''}`}>
        <div className="flex items-center gap-2">
          <span className={`text-sm mb-1 ${changed ? 'text-teal-300 font-medium' : 'text-gray-300'}`}>{displayLabel}</span>
          {changed && <ResetBtn onClick={() => onReset(def.key)} />}
        </div>
        <textarea value={firstVal(value)} onChange={e => onChange(def.key, e.target.value)}
          rows={6} spellCheck={false}
          className={`w-full px-2 py-1.5 border rounded text-xs text-green-300 font-mono
            focus:outline-none focus:ring-1 focus:ring-teal-500 resize-y
            ${changed ? 'bg-teal-900/20 border-teal-600' : 'bg-gray-900 border-gray-600'}`} />
      </div>
    );
  }

  // Notes
  if (def.key === 'filament_notes') {
    return (
      <div className="pt-2">
        <textarea value={firstVal(value)} onChange={e => onChange(def.key, e.target.value)}
          rows={16} placeholder="Add notes about this filament…"
          className="w-full px-3 py-2 bg-gray-900 border border-gray-600 rounded text-sm
            text-gray-200 focus:outline-none focus:ring-1 focus:ring-teal-500 resize-y font-mono" />
      </div>
    );
  }

  // Bool
  if (type === 'bool') {
    // Paired bool+int row (e.g. activate_air_filtration_during_print + during_print_exhaust_fan_speed)
    if (pairedDef && pairedDef.type !== 'bool') {
      return (
        <div className={`flex items-center gap-3 py-1.5 border-b border-gray-700/50 ${changed||pairedChg ? 'bg-teal-900/10' : ''}`}>
          <span className={`w-56 flex-shrink-0 text-sm ${changed ? 'text-teal-300 font-medium' : 'text-gray-300'}`}>{displayLabel}</span>
          <input type="checkbox" checked={boolVal(value)} onChange={e => onChange(def.key, e.target.checked ? '1':'0')} className="w-4 h-4 accent-teal-500" />
          {changed && <ResetBtn onClick={() => onReset(def.key)} />}
          <TextInput value={firstVal(pairedValue)} onChange={v => onChange(pairedDef.key, v)} className="w-20" changed={pairedChg} />
          {pairedDef.unit && <span className="text-xs text-gray-500">{pairedDef.unit}</span>}
          {pairedChg && <ResetBtn onClick={() => onReset(pairedDef.key)} />}
        </div>
      );
    }
    return (
      <div className={`flex items-center gap-3 py-1.5 border-b border-gray-700/50 ${changed ? 'bg-teal-900/10' : ''}`}>
        <span className={`w-56 flex-shrink-0 text-sm ${changed ? 'text-teal-300 font-medium' : 'text-gray-300'}`}>{displayLabel}</span>
        <input type="checkbox" checked={boolVal(value)} onChange={e => onChange(def.key, e.target.checked ? '1':'0')} className="w-4 h-4 accent-teal-500" />
        {changed && <ResetBtn onClick={() => onReset(def.key)} />}
      </div>
    );
  }

  // Enum
  if (type === 'enum' && def.options) {
    return (
      <div className={`flex items-center gap-3 py-1.5 border-b border-gray-700/50 ${changed ? 'bg-teal-900/10' : ''}`}>
        <span className={`w-56 flex-shrink-0 text-sm ${changed ? 'text-teal-300 font-medium' : 'text-gray-300'}`}>{displayLabel}</span>
        <SelectInput value={firstVal(value)||(def.options[0]?.value??'')} options={def.options}
          changed={changed} onChange={v => onChange(def.key, Array.isArray(value)?[v]:v)} />
        {changed && <ResetBtn onClick={() => onReset(def.key)} />}
      </div>
    );
  }

  // Float/Int/String with optional paired sibling (e.g. initial layer temp + layer temp)
  return (
    <div className={`flex items-center gap-3 py-1.5 border-b border-gray-700/50 ${changed||pairedChg ? 'bg-teal-900/10' : ''}`}>
      <span className={`w-56 flex-shrink-0 text-sm ${changed ? 'text-teal-300 font-medium' : 'text-gray-300'}`}>{displayLabel}</span>
      <div className="flex items-center gap-2 flex-1 min-w-0">
        <TextInput value={firstVal(value)} onChange={v => onChange(def.key, Array.isArray(value)?[v]:v)}
          className={pairedDef ? 'w-24' : undefined} changed={changed} />
        {changed && <ResetBtn onClick={() => onReset(def.key)} />}
        {pairedDef && (
          <>
            <span className="text-gray-500 text-xs flex-shrink-0">/</span>
            <TextInput value={firstVal(pairedValue)} onChange={v => onChange(pairedDef.key, Array.isArray(pairedValue)?[v]:v)}
              className="w-24" changed={pairedChg} />
            {pairedChg && <ResetBtn onClick={() => onReset(pairedDef.key)} />}
          </>
        )}
        {def.unit && <span className="text-xs text-gray-500 flex-shrink-0">{def.unit}</span>}
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Section
// ---------------------------------------------------------------------------

const Section: React.FC<{
  section: SectionDef; config: Record<string,unknown>; baseConfig: Record<string,unknown>;
  fieldMap: Map<string,FieldDef>;
  onChange: (k:string, v:unknown)=>void; onReset: (k:string)=>void;
}> = ({ section, config, baseConfig, fieldMap, onChange, onReset }) => {
  if (!section.fields.length) return null;
  return (
    <div>
      <div className="flex items-center gap-2 py-2 mt-3 mb-1">
        <span className="text-sm font-semibold text-white">{section.label}</span>
        <div className="flex-1 h-px bg-gray-600" />
      </div>
      {section.fields.filter(f => !PAIRED_SECONDARY.has(f.key)).map(def => {
        const pairedKey  = PAIRED_ROWS[def.key];
        const pairedDef  = pairedKey ? fieldMap.get(pairedKey) : undefined;
        const rowLabel   = PAIRED_ROW_LABELS[def.key];
        return (
          <FieldRow key={def.key} def={def}
            value={config[def.key]} baseValue={baseConfig[def.key]}
            pairedDef={pairedDef}
            pairedValue={pairedKey ? config[pairedKey] : undefined}
            pairedBaseValue={pairedKey ? baseConfig[pairedKey] : undefined}
            rowLabel={rowLabel}
            onChange={onChange} onReset={onReset} />
        );
      })}
    </div>
  );
};

// ---------------------------------------------------------------------------
// Main dialog
// ---------------------------------------------------------------------------

export interface FilamentConfigDialogProps {
  isOpen: boolean;
  onClose: () => void;
  /** Profile path e.g. "Bambu Lab/filament/Bambu PLA Basic @BBL A1M.json" */
  profilePath: string | null;
  filamentName: string;
  /** 0-based index of this filament in the selected filaments list — determines autosave filename */
  filamentIndex: number;
}

export type FilamentConfig = Record<string, unknown>;

export const FilamentConfigDialog: React.FC<FilamentConfigDialogProps> = ({
  isOpen, onClose, profilePath, filamentName, filamentIndex,
}) => {
  const [schema, setSchema]               = useState<OptionsDef | null>(null);
  const [activeTabId, setActiveTabId]     = useState<string>('filament');
  const [baseConfig, setBaseConfig]       = useState<Record<string,unknown>>({});
  const [config, setConfig]               = useState<Record<string,unknown>>({});
  const [inheritsValue, setInheritsValue] = useState<string>('');
  const [loading, setLoading]             = useState(false);
  const [configName, setConfigName]       = useState('');
  const [saveStatus, setSaveStatus]       = useState<'idle'|'saving'|'saved'|'error'>('idle');
  const [saveAsOpen, setSaveAsOpen]       = useState(false);
  const autosaveTimer                     = useRef<ReturnType<typeof setTimeout>|null>(null);
  const isFirstLoad                       = useRef(true);

  // Load schema once
  useEffect(() => {
    fetch('/data/filament_config_dialog_options.json')
      .then(r => r.json())
      .then((d: OptionsDef) => setSchema(d))
      .catch(err => console.error('Failed to load filament config schema:', err));
  }, []);

  // Load profile when dialog opens.
  // Always derives baseConfig from the selected profile (resolved).
  // Attempts to load a prior autosave on top of baseConfig so edits
  // persist across close → reopen without requiring an explicit Save.
  useEffect(() => {
    if (!isOpen || !profilePath || !schema) return;
    isFirstLoad.current = true;
    setLoading(true);
    setSaveStatus('idle');

    // Fixed autosave name for this filament slot: filament_1, filament_2, ...
    const autosaveName = `filament_${filamentIndex + 1}`;

    const schemaDefaults: Record<string,unknown> = {};
    schema.tabs.forEach(tab => tab.sections.forEach(sec => sec.fields.forEach(f => {
      if ((f.default ?? '') !== '') schemaDefaults[f.key] = f.default;
    })));

    const authHeader = { Authorization: `Bearer ${localStorage.getItem('api_token') || ''}` };
    const isUserConfig = profilePath.startsWith('user:');

    const doLoad = async () => {
      // ── 1. Resolve baseConfig from the currently selected profile ──────
      let base: Record<string,unknown> = { ...schemaDefaults };
      let effectiveInherits = '';

      if (isUserConfig) {
        const cfgName = profilePath.slice('user:'.length);
        setConfigName(cfgName);
        const userConfig: Record<string,unknown> = await apiClient.getFilamentConfig(cfgName, false);
        const inherits = userConfig.inherits as string | undefined;
        effectiveInherits = inherits ?? '';

        if (inherits) {
          const allProfiles: Array<{name:string; path:string}> = await fetch('/api/profiles', { headers: authHeader }).then(r => r.json());
          const parent = allProfiles.find(p => p.name === inherits && p.path.includes('/filament/'));
          if (parent) {
            const pts = parent.path.split('/');
            const resolved = await apiClient.getResolvedProfile(pts[0], pts[1], pts.slice(2).join('/'));
            base = { ...base, ...resolved };
          }
        }
        // User config itself forms the base (no unsaved changes from user config perspective)
        base = { ...base, ...userConfig };
      } else {
        const parts        = profilePath.split('/');
        const manufacturer = parts[0];
        const category     = parts[1];
        const filename     = parts.slice(2).join('/');
        setConfigName(filename.replace(/\.json$/, ''));

        const [resolved, raw] = await Promise.all([
          apiClient.getResolvedProfile(manufacturer, category, filename),
          fetch(`/api/profiles/${manufacturer}/${category}/${encodeURIComponent(filename)}`, { headers: authHeader }).then(r => r.json()),
        ]);
        base = { ...base, ...resolved };
        effectiveInherits = raw.name ?? raw.inherits ?? '';
      }

      setBaseConfig(base);
      setInheritsValue(effectiveInherits);

      // ── 2. Try loading prior autosave — overlay on base ────────────────
      try {
        const autosaved = await apiClient.getAutosave(autosaveName);
        // autosaved contains only the diff + inherits; overlay on base
        setConfig({ ...base, ...autosaved });
      } catch {
        // No autosave yet — start fresh from base
        setConfig({ ...base });
      }
    };

    doLoad()
      .catch(err => console.error('Failed to load filament config:', err))
      .finally(() => { setLoading(false); isFirstLoad.current = false; });

  }, [isOpen, profilePath, schema, filamentIndex]);

  const changedKeys = useCallback((): Set<string> => {
    const s = new Set<string>();
    for (const k of Object.keys(config)) {
      if (!valuesEqual(config[k], baseConfig[k])) s.add(k);
    }
    return s;
  }, [config, baseConfig]);

  const buildSavePayload = useCallback((): Record<string,unknown> => {
    const changed = changedKeys();
    const payload: Record<string,unknown> = {};
    if (inheritsValue) payload['inherits'] = inheritsValue;
    if (changed.size === 0) {
      Object.assign(payload, config);
    } else {
      for (const k of changed) payload[k] = config[k];
    }
    return payload;
  }, [config, changedKeys, inheritsValue]);

  // Debounced autosave — saves only the diff to fixed name filament_N
  useEffect(() => {
    if (isFirstLoad.current || !isOpen || !profilePath) return;
    const autosaveName = `filament_${filamentIndex + 1}`;
    if (autosaveTimer.current) clearTimeout(autosaveTimer.current);
    autosaveTimer.current = setTimeout(() => {
      const payload = buildSavePayload();
      apiClient.saveAutosave(autosaveName, payload)
        .catch(err => console.error('Filament autosave failed:', err));
    }, 800);
    return () => { if (autosaveTimer.current) clearTimeout(autosaveTimer.current); };
  }, [config, isOpen, profilePath, filamentIndex, buildSavePayload]);

  const handleChange = useCallback((key: string, value: unknown) => {
    setConfig(prev => ({ ...prev, [key]: value }));
  }, []);

  const handleReset = useCallback((key: string) => {
    setConfig(prev => ({ ...prev, [key]: baseConfig[key] }));
  }, [baseConfig]);

  const handleSave = () => setSaveAsOpen(true);

  const handleSaveConfirm = async (name: string) => {
    setSaveAsOpen(false);
    setConfigName(name);
    setSaveStatus('saving');
    try {
      await apiClient.saveFilamentConfig(name, buildSavePayload(), false);
      setBaseConfig({ ...config });
      setSaveStatus('saved');
      setTimeout(() => setSaveStatus('idle'), 2000);
    } catch {
      setSaveStatus('error');
      setTimeout(() => setSaveStatus('idle'), 3000);
    }
  };

  if (!isOpen) return null;

  const activeTab   = schema?.tabs.find(t => t.id === activeTabId) ?? null;
  const changed     = changedKeys();
  const changeCount = changed.size;

  const fieldMap = new Map<string, FieldDef>();
  schema?.tabs.forEach(tab => tab.sections.forEach(sec => sec.fields.forEach(f => fieldMap.set(f.key, f))));

  return (
    <>
    <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-[9999]"
      onClick={e => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="bg-gray-800 rounded-lg shadow-2xl flex flex-col w-[820px] max-w-[95vw] max-h-[90vh]">

        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3 border-b border-gray-700 flex-shrink-0">
          <span className="text-white font-semibold text-base truncate flex-1 min-w-0 mr-4">
            Filament settings — {filamentName}
          </span>
          <div className="flex items-center gap-2">
            {changeCount > 0 && (
              <span className="text-xs text-teal-400 bg-teal-900/40 border border-teal-700 px-2 py-0.5 rounded">
                {changeCount} change{changeCount !== 1 ? 's' : ''}
              </span>
            )}
            <button onClick={handleSave} disabled={saveStatus === 'saving'}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-teal-600 hover:bg-teal-500
                disabled:opacity-50 text-white text-sm rounded transition-colors">
              <Save className="w-4 h-4" />
              {saveStatus === 'saving' ? 'Saving…' : saveStatus === 'saved' ? 'Saved ✓' : saveStatus === 'error' ? 'Error!' : 'Save…'}
            </button>
            <button onClick={onClose} className="text-gray-400 hover:text-white p-1 rounded">
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Based on + autosave hint */}
        <div className="flex items-center gap-3 px-5 py-2 border-b border-gray-700 flex-shrink-0 text-xs text-gray-500">
          {inheritsValue && (
            <span className="truncate" title={`inherits: ${inheritsValue}`}>
              Based on: <span className="text-gray-400">{inheritsValue}</span>
            </span>
          )}
          <span className="ml-auto flex-shrink-0">
            {saveStatus === 'idle' && changeCount > 0 ? 'autosaved' : ''}
          </span>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-gray-700 flex-shrink-0 px-5 overflow-x-auto">
          {(schema?.tabs ?? []).map(tab => {
            const tabChanges = tab.sections.reduce((n, sec) =>
              n + sec.fields.filter(f => changed.has(f.key)).length, 0);
            return (
              <button key={tab.id} onClick={() => setActiveTabId(tab.id)}
                className={`px-3 py-2 text-sm font-medium border-b-2 transition-colors -mb-px whitespace-nowrap flex items-center gap-1.5 ${
                  activeTabId === tab.id ? 'border-teal-500 text-teal-400' : 'border-transparent text-gray-400 hover:text-gray-200'
                }`}>
                {tab.label}
                {tabChanges > 0 && (
                  <span className="text-xs bg-teal-700 text-teal-100 px-1.5 py-0.5 rounded-full leading-none">
                    {tabChanges}
                  </span>
                )}
              </button>
            );
          })}
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-5 py-3">
          {loading || !schema ? (
            <div className="flex items-center justify-center h-32 text-gray-400 text-sm">
              {schema ? 'Loading filament configuration…' : 'Loading schema…'}
            </div>
          ) : activeTab ? (
            activeTab.sections.map(section => (
              <Section key={section.label} section={section}
                config={config} baseConfig={baseConfig} fieldMap={fieldMap}
                onChange={handleChange} onReset={handleReset} />
            ))
          ) : null}
        </div>
      </div>
    </div>
    <SaveAsDialog isOpen={saveAsOpen} defaultName={`${configName} - copy`}
      onConfirm={handleSaveConfirm} onCancel={() => setSaveAsOpen(false)} />
    </>
  );
};
