/**
 * PrinterConfigDialog
 *
 * Data-driven printer settings editor.  The tab/section/field structure is
 * loaded at runtime from /data/printer_config_dialog_options.json, which is
 * generated by scripts/extract_printer_config_options.py from the OrcaSlicer
 * Tab.cpp and PrintConfig.cpp source files.
 *
 * Change tracking:
 *   - baseConfig  = fully resolved profile (inherits chain merged) + schema defaults
 *   - userEdits   = set of keys the user has changed from baseConfig
 *   - save/autosave writes only changed keys, plus "inherits" from the raw profile
 *
 * To update field definitions after an OrcaSlicer source upgrade, run:
 *   python3 scripts/extract_printer_config_options.py
 */

import React, { useEffect, useRef, useState, useCallback } from 'react';
import { X, Save, ChevronDown, RotateCcw } from 'lucide-react';
import { apiClient } from '../../api/client';
import { useStore } from '../../store';

// ---------------------------------------------------------------------------
// Save As dialog
// ---------------------------------------------------------------------------

interface SaveAsDialogProps {
  isOpen: boolean;
  defaultName: string;
  onConfirm: (name: string) => void;
  onCancel: () => void;
}

const SaveAsDialog: React.FC<SaveAsDialogProps> = ({ isOpen, defaultName, onConfirm, onCancel }) => {
  const [name, setName] = useState(defaultName);

  // Reset name whenever dialog opens with a new default
  useEffect(() => { if (isOpen) setName(defaultName); }, [isOpen, defaultName]);

  if (!isOpen) return null;
  return (
    <div className="fixed inset-0 bg-black/70 flex items-center justify-center z-[10000]"
      onClick={e => { if (e.target === e.currentTarget) onCancel(); }}>
      <div className="bg-gray-800 rounded-lg shadow-2xl p-6 w-[440px] max-w-[95vw]">
        <h2 className="text-white font-semibold text-base mb-4">Save printer config</h2>
        <label className="block text-sm text-gray-300 mb-1">Config name</label>
        <input
          type="text"
          value={name}
          onChange={e => setName(e.target.value)}
          onKeyDown={e => { if (e.key === 'Enter' && name.trim()) onConfirm(name.trim()); }}
          autoFocus
          className="w-full px-3 py-2 bg-gray-700 border border-gray-600 rounded text-sm text-white
            focus:outline-none focus:ring-1 focus:ring-teal-500 mb-5"
        />
        <div className="flex justify-end gap-3">
          <button onClick={onCancel}
            className="px-4 py-2 text-sm text-gray-300 bg-gray-700 hover:bg-gray-600 rounded transition-colors">
            Cancel
          </button>
          <button
            onClick={() => name.trim() && onConfirm(name.trim())}
            disabled={!name.trim()}
            className="px-4 py-2 text-sm text-white bg-teal-600 hover:bg-teal-500
              disabled:opacity-50 rounded transition-colors flex items-center gap-1.5">
            <Save className="w-4 h-4" />
            Save
          </button>
        </div>
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// JSON schema types
// ---------------------------------------------------------------------------

interface FieldOption  { value: string; label: string }
interface FieldDef     {
  key: string; label: string;
  type: string;               // float | int | bool | enum | string | gcode | point
  unit?: string;
  options?: FieldOption[];
  default?: string;
}
interface SectionDef   { label: string; fields: FieldDef[] }
interface TabDef       { id: string; label: string; sections: SectionDef[] }
interface OptionsDef   { tabs: TabDef[] }

// ---------------------------------------------------------------------------
// Paired-row rendering (two fields on one row)
// ---------------------------------------------------------------------------

const PAIRED_ROWS: Record<string, string> = {
  fan_speedup_time:               'fan_speedup_overhangs',
  input_shaping_freq_x:           'input_shaping_freq_y',
  input_shaping_damp_x:           'input_shaping_damp_y',
  min_resonance_avoidance_speed:  'max_resonance_avoidance_speed',
};
const PAIRED_SECONDARY = new Set(Object.values(PAIRED_ROWS));

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function firstVal(v: unknown): string {
  if (v === undefined || v === null) return '';
  if (Array.isArray(v)) {
    const first = v[0];
    return (first === undefined || first === null) ? '' : String(first);
  }
  return String(v);
}

function boolVal(v: unknown): boolean {
  const s = firstVal(v).toLowerCase();
  return s === '1' || s === 'true';
}

/** Deep-equal two config values (handles arrays). */
function valuesEqual(a: unknown, b: unknown): boolean {
  const sa = firstVal(a);
  const sb = firstVal(b);
  return sa === sb;
}

// ---------------------------------------------------------------------------
// Input primitives
// ---------------------------------------------------------------------------

const TextInput: React.FC<{
  value: string; onChange: (v: string) => void;
  placeholder?: string; className?: string; changed?: boolean;
}> = ({ value, onChange, placeholder, className, changed }) => (
  <input
    type="text"
    value={value}
    onChange={e => onChange(e.target.value)}
    placeholder={placeholder}
    className={`px-2 py-1 border rounded text-sm text-white focus:outline-none focus:ring-1
      focus:ring-teal-500 w-full transition-colors
      ${changed
        ? 'bg-teal-900/40 border-teal-500'
        : 'bg-gray-700 border-gray-600'}
      ${className ?? ''}`}
  />
);

const SelectInput: React.FC<{
  value: string; options: FieldOption[]; onChange: (v: string) => void; changed?: boolean;
}> = ({ value, options, onChange, changed }) => {
  const cleanLabel = (s: string) =>
    s.replace(/^L\(u?8?"(.+)"\)$/, '$1').replace(/^L\("(.+)"$/, '$1');
  return (
    <div className="relative flex-1">
      <select
        value={value}
        onChange={e => onChange(e.target.value)}
        className={`w-full px-2 py-1 border rounded text-sm text-white focus:outline-none
          focus:ring-1 focus:ring-teal-500 appearance-none pr-7 transition-colors
          ${changed ? 'bg-teal-900/40 border-teal-500' : 'bg-gray-700 border-gray-600'}`}
      >
        {options.map(o => <option key={o.value} value={o.value}>{cleanLabel(o.label)}</option>)}
      </select>
      <ChevronDown className="absolute right-2 top-1/2 -translate-y-1/2 w-3 h-3 text-gray-400 pointer-events-none" />
    </div>
  );
};

/** Small reset button shown next to changed fields. */
const ResetBtn: React.FC<{ onClick: () => void }> = ({ onClick }) => (
  <button
    onClick={onClick}
    title="Reset to original value"
    className="flex-shrink-0 p-1 rounded text-teal-400 hover:text-white hover:bg-gray-700 transition-colors"
  >
    <RotateCcw className="w-3.5 h-3.5" />
  </button>
);

// ---------------------------------------------------------------------------
// Single field row — change-aware
// ---------------------------------------------------------------------------

interface FieldRowProps {
  def: FieldDef;
  value: unknown;
  baseValue: unknown;       // original resolved value
  pairedDef?: FieldDef;
  pairedValue?: unknown;
  pairedBaseValue?: unknown;
  onChange: (key: string, v: unknown) => void;
  onReset: (key: string) => void;
}

const FieldRow: React.FC<FieldRowProps> = ({
  def, value, baseValue, pairedDef, pairedValue, pairedBaseValue, onChange, onReset,
}) => {
  const type    = def.type;
  const changed = !valuesEqual(value, baseValue);
  const pairedChanged = pairedDef ? !valuesEqual(pairedValue, pairedBaseValue) : false;

  // G-code textarea
  if (type === 'gcode') {
    return (
      <div className={`flex flex-col gap-1 py-2 border-b border-gray-700/50 ${changed ? 'bg-teal-900/10' : ''}`}>
        <div className="flex items-center gap-2">
          <span className={`text-sm mb-1 ${changed ? 'text-teal-300 font-medium' : 'text-gray-300'}`}>{def.label}</span>
          {changed && <ResetBtn onClick={() => onReset(def.key)} />}
        </div>
        <textarea
          value={firstVal(value)}
          onChange={e => onChange(def.key, e.target.value)}
          rows={6}
          spellCheck={false}
          className={`w-full px-2 py-1.5 border rounded text-xs text-green-300 font-mono
            focus:outline-none focus:ring-1 focus:ring-teal-500 resize-y
            ${changed ? 'bg-teal-900/20 border-teal-600' : 'bg-gray-900 border-gray-600'}`}
        />
      </div>
    );
  }

  // Notes
  if (def.key === 'printer_notes') {
    return (
      <div className="pt-2">
        <textarea
          value={firstVal(value)}
          onChange={e => onChange(def.key, e.target.value)}
          rows={16}
          placeholder="Add notes about this printer…"
          className="w-full px-3 py-2 bg-gray-900 border border-gray-600 rounded text-sm
            text-gray-200 focus:outline-none focus:ring-1 focus:ring-teal-500 resize-y font-mono"
        />
      </div>
    );
  }

  // Printable area (special array-of-points rendering)
  if (def.key === 'printable_area') {
    const areaStr = Array.isArray(value)
      ? (value as unknown[]).map(p => Array.isArray(p) ? (p as unknown[]).join(',') : String(p)).join(' ')
      : firstVal(value);
    return (
      <div className={`flex items-center gap-3 py-1.5 border-b border-gray-700/50 ${changed ? 'bg-teal-900/10' : ''}`}>
        <span className={`w-56 flex-shrink-0 text-sm ${changed ? 'text-teal-300 font-medium' : 'text-gray-300'}`}>{def.label}</span>
        <TextInput value={areaStr} onChange={v => onChange(def.key, v)} placeholder="0,0 300,0 300,300 0,300" changed={changed} />
        {changed && <ResetBtn onClick={() => onReset(def.key)} />}
      </div>
    );
  }

  // Bool checkbox
  if (type === 'bool') {
    // Paired bool (e.g. fan_speedup_time + fan_speedup_overhangs)
    if (pairedDef && pairedDef.type === 'bool') {
      return (
        <div className={`flex items-center gap-3 py-1.5 border-b border-gray-700/50 ${changed || pairedChanged ? 'bg-teal-900/10' : ''}`}>
          <span className={`w-56 flex-shrink-0 text-sm ${changed ? 'text-teal-300 font-medium' : 'text-gray-300'}`}>{def.label}</span>
          <input type="checkbox" checked={boolVal(value)} onChange={e => onChange(def.key, e.target.checked ? '1' : '0')} className="w-4 h-4 accent-teal-500" />
          {changed && <ResetBtn onClick={() => onReset(def.key)} />}
          <label className={`flex items-center gap-1 text-xs ml-3 ${pairedChanged ? 'text-teal-300' : 'text-gray-400'}`}>
            <input type="checkbox" checked={boolVal(pairedValue)} onChange={e => onChange(pairedDef.key, e.target.checked ? '1' : '0')} className="accent-teal-500" />
            {pairedDef.label}
          </label>
          {pairedChanged && <ResetBtn onClick={() => onReset(pairedDef.key)} />}
        </div>
      );
    }
    return (
      <div className={`flex items-center gap-3 py-1.5 border-b border-gray-700/50 ${changed ? 'bg-teal-900/10' : ''}`}>
        <span className={`w-56 flex-shrink-0 text-sm ${changed ? 'text-teal-300 font-medium' : 'text-gray-300'}`}>{def.label}</span>
        <input type="checkbox" checked={boolVal(value)} onChange={e => onChange(def.key, e.target.checked ? '1' : '0')} className="w-4 h-4 accent-teal-500" />
        {changed && <ResetBtn onClick={() => onReset(def.key)} />}
      </div>
    );
  }

  // Enum select
  if (type === 'enum' && def.options) {
    return (
      <div className={`flex items-center gap-3 py-1.5 border-b border-gray-700/50 ${changed ? 'bg-teal-900/10' : ''}`}>
        <span className={`w-56 flex-shrink-0 text-sm ${changed ? 'text-teal-300 font-medium' : 'text-gray-300'}`}>{def.label}</span>
        <SelectInput
          value={firstVal(value) || (def.options[0]?.value ?? '')}
          options={def.options}
          changed={changed}
          onChange={v => onChange(def.key, Array.isArray(value) ? [v] : v)}
        />
        {changed && <ResetBtn onClick={() => onReset(def.key)} />}
      </div>
    );
  }

  // Float / Int / String — with optional paired sibling
  return (
    <div className={`flex items-center gap-3 py-1.5 border-b border-gray-700/50 ${changed || pairedChanged ? 'bg-teal-900/10' : ''}`}>
      <span className={`w-56 flex-shrink-0 text-sm ${changed ? 'text-teal-300 font-medium' : 'text-gray-300'}`}>{def.label}</span>
      <div className="flex items-center gap-2 flex-1 min-w-0">
        <TextInput
          value={firstVal(value)}
          onChange={v => onChange(def.key, Array.isArray(value) ? [v] : v)}
          className={pairedDef ? 'w-28' : undefined}
          changed={changed}
        />
        {changed && <ResetBtn onClick={() => onReset(def.key)} />}
        {pairedDef && (
          <>
            <span className="text-gray-500 text-xs flex-shrink-0">–</span>
            <TextInput
              value={firstVal(pairedValue)}
              onChange={v => onChange(pairedDef.key, Array.isArray(pairedValue) ? [v] : v)}
              className="w-28"
              changed={pairedChanged}
            />
            {pairedChanged && <ResetBtn onClick={() => onReset(pairedDef.key)} />}
          </>
        )}
        {def.unit && <span className="text-xs text-gray-500 flex-shrink-0">{def.unit}</span>}
      </div>
    </div>
  );
};

// ---------------------------------------------------------------------------
// Section
// ---------------------------------------------------------------------------

interface SectionProps {
  section: SectionDef;
  config: Record<string, unknown>;
  baseConfig: Record<string, unknown>;
  fieldMap: Map<string, FieldDef>;
  onChange: (key: string, v: unknown) => void;
  onReset: (key: string) => void;
}

const Section: React.FC<SectionProps> = ({ section, config, baseConfig, fieldMap, onChange, onReset }) => {
  if (section.fields.length === 0) return null;
  return (
    <div>
      <div className="flex items-center gap-2 py-2 mt-3 mb-1">
        <span className="text-sm font-semibold text-white">{section.label}</span>
        <div className="flex-1 h-px bg-gray-600" />
      </div>
      {section.fields
        .filter(f => !PAIRED_SECONDARY.has(f.key))
        .map(def => {
          const pairedKey  = PAIRED_ROWS[def.key];
          const pairedDef  = pairedKey ? fieldMap.get(pairedKey) : undefined;
          return (
            <FieldRow
              key={def.key}
              def={def}
              value={config[def.key]}
              baseValue={baseConfig[def.key]}
              pairedDef={pairedDef}
              pairedValue={pairedKey ? config[pairedKey] : undefined}
              pairedBaseValue={pairedKey ? baseConfig[pairedKey] : undefined}
              onChange={onChange}
              onReset={onReset}
            />
          );
        })}
    </div>
  );
};

// ---------------------------------------------------------------------------
// Main dialog
// ---------------------------------------------------------------------------

export interface PrinterConfigDialogProps {
  isOpen: boolean;
  onClose: () => void;
  profilePath: string | null;
  printerName: string;
}

export type PrinterConfig = Record<string, unknown>;

export const PrinterConfigDialog: React.FC<PrinterConfigDialogProps> = ({
  isOpen, onClose, profilePath, printerName,
}) => {
  const [schema, setSchema]           = useState<OptionsDef | null>(null);
  const [activeTabId, setActiveTabId] = useState<string>('basic');

  // baseConfig: fully resolved + schema defaults — the "before" state
  const [baseConfig, setBaseConfig]   = useState<Record<string, unknown>>({});
  // config: current editor state (user may have changed values)
  const [config, setConfig]           = useState<Record<string, unknown>>({});
  // inheritsValue: from the raw (unresolved) profile file, used when saving
  const [inheritsValue, setInheritsValue] = useState<string>('');

  const [loading, setLoading]         = useState(false);
  const [configName, setConfigName]   = useState('');
  const [saveStatus, setSaveStatus]   = useState<'idle'|'saving'|'saved'|'error'>('idle');
  const [saveAsOpen, setSaveAsOpen]   = useState(false);
  const autosaveTimer                 = useRef<ReturnType<typeof setTimeout>|null>(null);
  const isFirstLoad                   = useRef(true);

  // Load schema once
  useEffect(() => {
    fetch('/data/printer_config_dialog_options.json')
      .then(r => r.json())
      .then((d: OptionsDef) => setSchema(d))
      .catch(err => console.error('Failed to load printer config schema:', err));
  }, []);

  // Load profile when dialog opens.
  // baseConfig = resolved selected profile + schema defaults (the "before" baseline).
  // On open, we also try loading a prior autosave and overlay it on baseConfig so
  // close → reopen preserves edits without an explicit Save.
  useEffect(() => {
    if (!isOpen || !profilePath || !schema) return;
    isFirstLoad.current = true;
    setLoading(true);
    setSaveStatus('idle');

    const schemaDefaults: Record<string, unknown> = {};
    schema.tabs.forEach(tab =>
      tab.sections.forEach(sec =>
        sec.fields.forEach(f => {
          if ((f.default ?? '') !== '') schemaDefaults[f.key] = f.default;
        })
      )
    );

    const authHeader = { Authorization: `Bearer ${localStorage.getItem('api_token') || ''}` };
    const isUserConfig = profilePath.startsWith('user:');

    const doLoad = async () => {
      // ── 1. Resolve baseConfig from the currently selected profile ──────
      let base: Record<string,unknown> = { ...schemaDefaults };
      let effectiveInherits = '';

      if (isUserConfig) {
        const cfgName = profilePath.slice('user:'.length);
        setConfigName(cfgName);
        const userConfig: Record<string,unknown> = await apiClient.getPrinterConfig(cfgName, false);
        const inherits = userConfig.inherits as string | undefined;
        effectiveInherits = inherits ?? '';

        if (inherits) {
          const allProfiles: Array<{name:string;path:string}> = await fetch('/api/profiles', { headers: authHeader }).then(r => r.json());
          const parent = allProfiles.find(p => p.name === inherits && p.path.includes('/machine/'));
          if (parent) {
            const pts = parent.path.split('/');
            const resolved = await apiClient.getResolvedProfile(pts[0], pts[1], pts.slice(2).join('/'));
            base = { ...base, ...resolved };
          }
        }
        base = { ...base, ...userConfig };
      } else {
        const parts        = profilePath.split('/');
        const manufacturer = parts[0];
        const category     = parts[1];
        const filename     = parts.slice(2).join('/');
        setConfigName(filename.replace(/\.json$/, ''));

        const [resolved, raw] = await Promise.all([
          apiClient.getResolvedProfile(manufacturer, category, filename),
          fetch(`/api/profiles/${manufacturer}/${category}/${encodeURIComponent(filename)}`, { headers: authHeader }).then(r => r.json()),
        ]);
        base = { ...base, ...resolved };
        effectiveInherits = raw.name ?? raw.inherits ?? '';
      }

      setBaseConfig(base);
      setInheritsValue(effectiveInherits);

      // ── 2. Try loading prior autosave — overlay on base ────────────────
      // Only apply it if it belongs to the profile we're currently editing
      // (marked via `_profile_path`); otherwise it's a stale autosave left
      // over from editing a different printer profile and must be ignored.
      try {
        const autosaved = await apiClient.getAutosave('printer_config');
        const savedFor = autosaved['_profile_path'] as string | undefined;
        if (!savedFor || savedFor === profilePath) {
          setConfig({ ...base, ...autosaved });
        } else {
          setConfig({ ...base });
        }
      } catch {
        setConfig({ ...base });
      }
    };

    doLoad()
      .catch(err => console.error('Failed to load printer config:', err))
      .finally(() => { setLoading(false); isFirstLoad.current = false; });
  }, [isOpen, profilePath, schema]);

  // Compute changed keys (current vs base).
  // `inherits` and `_profile_path` are bookkeeping metadata added to the
  // autosave payload (see buildSavePayload) — they never exist on baseConfig,
  // so they must be excluded here or every reload of a prior autosave would
  // show 2 phantom "changes" even with no real edits.
  const changedKeys = useCallback((): Set<string> => {
    const changed = new Set<string>();
    for (const key of Object.keys(config)) {
      if (key === 'inherits' || key === '_profile_path') continue;
      if (!valuesEqual(config[key], baseConfig[key])) changed.add(key);
    }
    return changed;
  }, [config, baseConfig]);

  // Build save payload: only changed keys + inherits chain + a marker of
  // which profile these edits apply to, so a later reload (or slicing —
  // see backend cli_builder.py) can tell whether this autosave is stale.
  const buildSavePayload = useCallback((): Record<string, unknown> => {
    const changed = changedKeys();
    const payload: Record<string, unknown> = {};
    if (inheritsValue) payload['inherits'] = inheritsValue;
    if (profilePath) payload['_profile_path'] = profilePath;
    for (const key of changed) {
      payload[key] = config[key];
    }
    return payload;
  }, [config, changedKeys, inheritsValue, profilePath]);

  // Debounced autosave — saves only the diff to fixed name printer_config.
  // Skip entirely when there are no real field changes, so opening the
  // dialog and closing it without editing anything never writes an
  // autosave (which would otherwise reappear as phantom changes on reopen).
  useEffect(() => {
    if (isFirstLoad.current || !isOpen || !profilePath) return;
    if (autosaveTimer.current) clearTimeout(autosaveTimer.current);
    autosaveTimer.current = setTimeout(() => {
      if (changedKeys().size === 0) return;
      const payload = buildSavePayload();
      apiClient.saveAutosave('printer_config', payload)
        .catch(err => console.error('Printer autosave failed:', err));
    }, 800);
    return () => { if (autosaveTimer.current) clearTimeout(autosaveTimer.current); };
  }, [config, isOpen, profilePath, buildSavePayload, changedKeys]);

  const handleChange = useCallback((key: string, value: unknown) => {
    setConfig(prev => ({ ...prev, [key]: value }));
  }, []);

  const handleReset = useCallback((key: string) => {
    setConfig(prev => ({ ...prev, [key]: baseConfig[key] }));
  }, [baseConfig]);

  const handleSave = () => {
    // Open Save As dialog — user can confirm/edit the name
    setSaveAsOpen(true);
  };

  // Flush pending edits to the autosave immediately on close (bypassing
  // the 800ms debounce) so a quick edit-then-close never loses the last
  // keystroke, and re-save the session's user_config.yaml so the
  // autosave is embedded there too (see profileSlice.saveUserConfig) —
  // this is what lets Slice discover the edits without an explicit Save.
  const saveUserConfig = useStore((state) => state.saveUserConfig);
  const handleClose = useCallback(() => {
    if (autosaveTimer.current) {
      clearTimeout(autosaveTimer.current);
      autosaveTimer.current = null;
    }
    if (!isFirstLoad.current && profilePath && changedKeys().size > 0) {
      const payload = buildSavePayload();
      apiClient.saveAutosave('printer_config', payload)
        .then(() => saveUserConfig())
        .catch(err => console.error('Printer autosave-on-close failed:', err));
    }
    onClose();
  }, [profilePath, changedKeys, buildSavePayload, saveUserConfig, onClose]);

  const handleSaveConfirm = async (name: string) => {
    setSaveAsOpen(false);
    setConfigName(name);
    setSaveStatus('saving');
    try {
      const payload = buildSavePayload();
      await apiClient.savePrinterConfig(name, payload, false);
      // Commit: new base becomes current state so change indicators clear
      setBaseConfig({ ...config });
      setSaveStatus('saved');
      setTimeout(() => setSaveStatus('idle'), 2000);
    } catch {
      setSaveStatus('error');
      setTimeout(() => setSaveStatus('idle'), 3000);
    }
  };

  if (!isOpen) return null;

  const activeTab   = schema?.tabs.find(t => t.id === activeTabId) ?? null;
  const changed     = changedKeys();
  const changeCount = changed.size;
  // Default save-as name: base profile name + " - copy"
  const saveAsDefaultName = `${configName} - copy`;

  const fieldMap = new Map<string, FieldDef>();
  schema?.tabs.forEach(tab =>
    tab.sections.forEach(sec =>
      sec.fields.forEach(f => fieldMap.set(f.key, f))
    )
  );

  return (
    <>
    <div
      className="fixed inset-0 bg-black/60 flex items-center justify-center z-[9999]"
      onClick={e => { if (e.target === e.currentTarget) handleClose(); }}
    >
      <div className="bg-gray-800 rounded-lg shadow-2xl flex flex-col w-[820px] max-w-[95vw] max-h-[90vh]">

        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3 border-b border-gray-700 flex-shrink-0">
          <span className="text-white font-semibold text-base truncate flex-1 min-w-0 mr-4">
            Printer settings — {printerName}
          </span>
          <div className="flex items-center gap-2">
            {changeCount > 0 && (
              <span className="text-xs text-teal-400 bg-teal-900/40 border border-teal-700 px-2 py-0.5 rounded">
                {changeCount} change{changeCount !== 1 ? 's' : ''}
              </span>
            )}
            <button
              onClick={handleSave}
              disabled={saveStatus === 'saving' || changeCount === 0}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-teal-600 hover:bg-teal-500
                disabled:opacity-50 text-white text-sm rounded transition-colors"
            >
              <Save className="w-4 h-4" />
              {saveStatus === 'saving' ? 'Saving…'
                : saveStatus === 'saved'  ? 'Saved ✓'
                : saveStatus === 'error'  ? 'Error!'
                : 'Save…'}
            </button>
            <button onClick={handleClose} className="text-gray-400 hover:text-white p-1 rounded">
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* inherits info + autosave status */}
        <div className="flex items-center gap-3 px-5 py-2 border-b border-gray-700 flex-shrink-0 text-xs text-gray-500">
          {inheritsValue && (
            <span className="truncate" title={`inherits: ${inheritsValue}`}>
              Based on: <span className="text-gray-400">{inheritsValue}</span>
            </span>
          )}
          <span className="ml-auto flex-shrink-0">
            {saveStatus === 'idle' && changeCount > 0 ? 'autosaved' : ''}
          </span>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-gray-700 flex-shrink-0 px-5 overflow-x-auto">
          {(schema?.tabs ?? []).map(tab => {
            // Count changes in this tab
            const tabChanges = tab.sections.reduce((n, sec) =>
              n + sec.fields.filter(f => changed.has(f.key)).length, 0);
            return (
              <button
                key={tab.id}
                onClick={() => setActiveTabId(tab.id)}
                className={`px-3 py-2 text-sm font-medium border-b-2 transition-colors -mb-px whitespace-nowrap flex items-center gap-1.5 ${
                  activeTabId === tab.id
                    ? 'border-teal-500 text-teal-400'
                    : 'border-transparent text-gray-400 hover:text-gray-200'
                }`}
              >
                {tab.label}
                {tabChanges > 0 && (
                  <span className="text-xs bg-teal-700 text-teal-100 px-1.5 py-0.5 rounded-full leading-none">
                    {tabChanges}
                  </span>
                )}
              </button>
            );
          })}
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto px-5 py-3">
          {loading || !schema ? (
            <div className="flex items-center justify-center h-32 text-gray-400 text-sm">
              {schema ? 'Loading printer configuration…' : 'Loading schema…'}
            </div>
          ) : activeTab ? (
            activeTab.sections.map(section => (
              <Section
                key={section.label}
                section={section}
                config={config}
                baseConfig={baseConfig}
                fieldMap={fieldMap}
                onChange={handleChange}
                onReset={handleReset}
              />
            ))
          ) : null}
        </div>
      </div>
    </div>
    <SaveAsDialog
      isOpen={saveAsOpen}
      defaultName={saveAsDefaultName}
      onConfirm={handleSaveConfirm}
      onCancel={() => setSaveAsOpen(false)}
    />
    </>
  );
};
